### ISSUE TITLE
Throw an error on bad JSON return

### ISSUE THREAD

**Issue by Qqwy** [Tschaul/twister-lib-js#1]
I tried this library out, but had problems with a syntax error that was thrown. It took me quite a bit of debugging before I figured out that the JSON.parse method on (in this case) r.283 of twisterResource.js was not placed within a try/catch statement.

What happened was, my RPC info was wrong, so the server answered with a 401 error instead of proper JSON. It would be great to display/throw a custom error message in this case, I think.

other than that: Great work! The examples are wonderful :-).

**Comment by Tschaul** [comment]
Strange, the 401 http error code should have been caught by the `if(error)` clause (https://github.com/Tschaul/twister-lib-js/blob/master/src/TwisterResource.js#L233). I will look into that.

**Comment by Tschaul** [comment]
Is fixed. Non 2xx status codes are now thrown as error that include the error code. And the try catch statement is also implemented.
